name: 'piuparts'
author: 'Evgeni Golov'
description: 'Run piuparts on a Debian package'
inputs:
  package:
    description: 'The package to run piuparts on'
    default: '*.changes'
  base-image:
    description: 'The base-image to run piuparts in'
    default: 'debian:sid'
  fake-essential-packages:
    description: 'Packages that should be added to the fake-essential-packages list'
    default: ''
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.package }}
    - ${{ inputs.base-image }}
    - ${{ inputs.fake-essential-packages }}
branding:
  icon: 'repeat'
  color: 'purple'
