name: CI

on:
  - push
  - pull_request

jobs:
  test:
    runs-on: ubuntu-latest
    container: debian:sid
    steps:
      - uses: actions/checkout@v3
      - name: get hello package
        run: |
          apt-get update
          apt-get download hello
      - name: run piuparts
        uses: ./
        with:
          package: 'hello_*.deb'
